Repository microsoft/kernel-memory, pull requests merged in 2023-09, with the labels that each got.

#44 Read config from env and secrets
  dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
  dotnet/CoreLib/CoreLib.csproj
Labels: enhancement

#46 Add simple vector DB to service
  dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
Labels: bug

#48 Consider min relevance score in simple vector db
  dotnet/CoreLib/MemoryStorage/DevTools/SimpleVectorDb.cs
Labels: bug

#54 Allow skip of summarize handler during client setup.
  dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
Labels: enhancement

#51 Add volatile memory storage
  dotnet/CoreLib/MemoryStorage/DevTools/ISimpleStorage.cs
  dotnet/CoreLib/MemoryStorage/DevTools/SimpleVectorDb.cs
  dotnet/CoreLib/MemoryStorage/DevTools/SimpleVectorDbConfig.cs
  dotnet/Service/appsettings.json
  examples/004-dotnet-ServerlessCustomPipeline/appsettings.json
  examples/005-dotnet-InProcessMemoryWithCustomHandler/appsettings.json
  examples/006-dotnet-CustomHandlerAsAService/appsettings.json
  tests/FunctionalTests/appsettings.json
Labels: enhancement

#56 Bug fixes, package updates, and readme enhancements
  examples/200-dotnet-nl2sql/Nl2Sql.sln
  examples/200-dotnet-nl2sql/README.md
  examples/200-dotnet-nl2sql/nl2sql.config/README.md
  examples/200-dotnet-nl2sql/nl2sql.config/nl2sql/generatequery/skprompt.txt
  examples/200-dotnet-nl2sql/nl2sql.config/schema/README.md
  examples/200-dotnet-nl2sql/nl2sql.console/appsettings.json
  examples/200-dotnet-nl2sql/nl2sql.harness/Nl2Sql.Harness.csproj
  examples/200-dotnet-nl2sql/nl2sql.harness/SqlSchemaProviderHarness.cs
  examples/200-dotnet-nl2sql/nl2sql.library/Internal/SKContextExtensions.cs
  examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
  examples/200-dotnet-nl2sql/nl2sql.library/SqlQueryGenerator.cs
Labels: bug, documentation, enhancement, question, sample

#63 Flag messages being processed in SimpleQueues
  dotnet/CoreLib/Pipeline/Queue/DevTools/SimpleQueues.cs
Labels: bug

#43 Leverage NuGet central package management
  Directory.Packages.props
  SemanticMemory.sln
  dotnet/ClientLib/ClientLib.csproj
  dotnet/CoreLib/CoreLib.csproj
  dotnet/InteractiveSetup/InteractiveSetup.csproj
  dotnet/Service/Service.csproj
  dotnet/nuget/nuget-package.props
  examples/001-dotnet-Serverless/001-dotnet-Serverless.csproj
  examples/002-dotnet-WebClient/002-dotnet-WebClient.csproj
  examples/004-dotnet-ServerlessCustomPipeline/004-dotnet-ServerlessCustomPipeline.csproj
  examples/005-dotnet-InProcessMemoryWithCustomHandler/005-dotnet-InProcessMemoryWithCustomHandler.csproj
  examples/006-dotnet-CustomHandlerAsAService/006-dotnet-CustomHandlerAsAService.csproj
  examples/102-using-azure-cognitive-search/102-using-azure-cognitive-search.csproj
  examples/103-using-qdrant/103-using-qdrant.csproj
  examples/104-dotnet-ExtractTextFromDocs/104-dotnet-ExtractTextFromDocs.csproj
  examples/200-dotnet-nl2sql/nl2sql.console/Nl2Sql.Console.csproj
  examples/200-dotnet-nl2sql/nl2sql.harness/Nl2Sql.Harness.csproj
  examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
  nuget.config
  tests/FunctionalTests/FunctionalTests.csproj
Labels: enhancement
