Repository microsoft/kernel-memory, pull requests merged in 2023-08, with the labels that each got.

#16 Change icon and readme paths to absolute in common props paths
  dotnet/nuget/nuget-package.props
Labels: bug

#20 Fix publish workflow
  .github/workflows/publish.yaml
Labels: bug

#21 Set publish workflow dotnet version to 7
  .github/workflows/publish.yaml
Labels: bug

#22 Update regex for dotnet nuget push to push the correct packages
  .github/workflows/publish.yaml
Labels: bug

#28 Unreverse prompts and introduce relevance option (not hardcoded)
  .github/_typos.toml
  README.md
  dotnet/Service/README.md
  examples/200-dotnet-nl2sql/nl2sql.config/nl2sql/generatequery/skprompt.txt
  examples/200-dotnet-nl2sql/nl2sql.config/nl2sql/isquery/skprompt.txt
  examples/200-dotnet-nl2sql/nl2sql.console/Nl2SqlConsole.cs
  examples/200-dotnet-nl2sql/nl2sql.console/appsettings.json
  examples/200-dotnet-nl2sql/nl2sql.library/SqlQueryGenerator.cs
Labels: bug, sample

#29 Add Image OCR Support
  dotnet/ClientLib/ClientLib.csproj
  dotnet/CoreLib/AppBuilders/MemoryClientBuilder.cs
  dotnet/CoreLib/Configuration/SemanticMemoryConfig.cs
  dotnet/CoreLib/CoreLib.csproj
  dotnet/CoreLib/DataFormats/Image/AzureFormRecognizer/AzureFormRecognizerConfig.cs
  dotnet/CoreLib/DataFormats/Image/AzureFormRecognizer/AzureFormRecognizerEngine.cs
  dotnet/CoreLib/DataFormats/Image/AzureFormRecognizer/DependencyInjection.cs
  dotnet/CoreLib/DataFormats/Image/IOcrEngine.cs
  dotnet/CoreLib/DataFormats/Image/ImageDecoder.cs
  dotnet/CoreLib/DataFormats/Office/MsWordDecoder.cs
  dotnet/CoreLib/DataFormats/Pdf/PdfDecoder.cs
  dotnet/CoreLib/Handlers/TextExtractionHandler.cs
  dotnet/CoreLib/Memory.cs
  dotnet/CoreLib/Pipeline/BaseOrchestrator.cs
  dotnet/CoreLib/Pipeline/MimeTypes.cs
  dotnet/Service/appsettings.json
  examples/001-dotnet-Serverless/Program.cs
Labels: enhancement

#32 Update Semantic Kernel to 0.21.230828.2-preview
  dotnet/CoreLib/AI/AzureOpenAI/DependencyInjection.cs
  dotnet/CoreLib/AI/OpenAI/DependencyInjection.cs
  dotnet/CoreLib/AI/Tokenizers/GPT3/GPT3Settings.cs
  dotnet/CoreLib/ContentStorage/EmbeddingFileContent.cs
  dotnet/CoreLib/CoreLib.csproj
  dotnet/CoreLib/Handlers/GenerateEmbeddingsHandler.cs
  dotnet/CoreLib/Handlers/SaveEmbeddingsHandler.cs
  dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemory.cs
  dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemoryRecord.cs
  dotnet/CoreLib/MemoryStorage/DevTools/SimpleVectorDb.cs
  dotnet/CoreLib/MemoryStorage/ISemanticMemoryVectorDb.cs
  dotnet/CoreLib/MemoryStorage/MemoryRecord.cs
  dotnet/CoreLib/MemoryStorage/Qdrant/Client/Http/HttpRequest.cs
  dotnet/CoreLib/MemoryStorage/Qdrant/Client/QdrantPoint.cs
  dotnet/CoreLib/MemoryStorage/Qdrant/QdrantMemory.cs
  dotnet/CoreLib/Search/SearchClient.cs
  dotnet/CoreLib/Text/ReadOnlyMemoryConverter.cs
  examples/102-using-azure-cognitive-search/Program.cs
  examples/103-using-qdrant/Program.cs
  examples/200-dotnet-nl2sql/nl2sql.console/KernelFactory.cs
  examples/200-dotnet-nl2sql/nl2sql.library/Nl2Sql.Library.csproj
  tests/FunctionalTests/VectorDbComparison/TestCosineSimilarity.cs
Labels: enhancement
