Repository microsoft/kernel-memory, pull requests merged in 2024-05, with the labels that each got.

#415 Export/Download document support
  Directory.Packages.props
  clients/dotnet/WebClient/MemoryWebClient.cs
  extensions/AzureAISearch/AzureAISearch.FunctionalTests/DefaultTests.cs
  extensions/AzureBlobs/AzureBlobsStorage.cs
  extensions/MongoDbAtlas/MongoDbAtlas.FunctionalTests/DefaultTests.cs
  extensions/MongoDbAtlas/MongoDbAtlas/MongoDbAtlasStorage.cs
  extensions/Postgres/Postgres.FunctionalTests/DefaultTests.cs
  extensions/Qdrant/Qdrant.FunctionalTests/DefaultTests.cs
  extensions/Redis/Redis.FunctionalTests/DefaultTests.cs
  service/Abstractions/Constants.cs
  service/Core/ContentStorage/DevTools/SimpleFileStorage.cs
  service/Core/FileSystem/DevTools/DiskFileSystem.cs
  service/Core/FileSystem/DevTools/IFileSystem.cs
  service/Core/FileSystem/DevTools/VolatileFileSystem.cs
  service/Core/MemoryServerless.cs
  service/Core/MemoryService.cs
  service/Core/MemoryStorage/DevTools/SimpleTextDb.cs
  service/Core/MemoryStorage/DevTools/SimpleVectorDb.cs
  service/Core/MemoryStorage/MemoryRecordExtensions.cs
  service/Core/Pipeline/BaseOrchestrator.cs
  service/Core/Pipeline/Queue/DevTools/SimpleQueues.cs
  service/Core/Search/SearchClient.cs
  service/Service.AspNetCore/Service.AspNetCore.csproj
  service/Service.AspNetCore/WebAPIEndpoints.cs
  service/tests/Abstractions.UnitTests/Abstractions.UnitTests.csproj
  service/tests/Abstractions.UnitTests/Models/FileCollectionTest.cs
  service/tests/Core.FunctionalTests/DefaultTestCases/DocumentUploadTest.cs
  service/tests/Core.FunctionalTests/Fixtures/Doc1.txt
  service/tests/Core.FunctionalTests/Fixtures/Documents/Doc1.txt
  service/tests/Core.FunctionalTests/Fixtures/Documents/Sales/Doc1.txt
  service/tests/Core.FunctionalTests/Fixtures/Documents/Support/Doc1.txt
  service/tests/Core.FunctionalTests/ServerLess/DefaultTests.cs
  service/tests/Core.FunctionalTests/ServerLess/SubDirFilesAndStreamsTest.cs
  service/tests/Core.UnitTests/FileSystem/DevTools/InMemoryFileSystemTest.cs
  service/tests/Core.UnitTests/FileSystem/DevTools/OnDiskFileSystemTest.cs
  service/tests/Service.FunctionalTests/DefaultTests.cs
Labels: waiting for author

#438 Azure AI Search: Add support for batching save operations
  extensions/AzureAISearch/AzureAISearch/AzureAISearchMemory.cs
  service/Core/Configuration/KernelMemoryConfig.cs
  service/Core/Handlers/SaveRecordsHandler.cs
  service/Service/appsettings.json
Labels: ready for review

#489 Add batch upsert support for SQL Server Memory DB
  extensions/SQLServer/README.md
  extensions/SQLServer/SQLServer/SqlServerMemory.cs
Labels: waiting for author, work in progress

#404 Adding Basic anthropic Claude support.
  KernelMemory.sln
  README.md
  docs/index.md
  examples/110-dotnet-anthropic/110-dotnet-anthropic.csproj
  examples/110-dotnet-anthropic/Program.cs
  examples/110-dotnet-anthropic/appsettings.json
  examples/110-dotnet-anthropic/file5-NASA-news.pdf
  examples/README.md
  extensions/Anthropic/Anthropic.csproj
  extensions/Anthropic/AnthropicConfiguration.cs
  extensions/Anthropic/AnthropicTextGeneration.cs
  extensions/Anthropic/Client/CallClaudeStreamingParams.cs
  extensions/Anthropic/Client/ContentBlockDelta.cs
  extensions/Anthropic/Client/ContentResponse.cs
  extensions/Anthropic/Client/Delta.cs
  extensions/Anthropic/Client/Message.cs
  extensions/Anthropic/Client/MessageRequest.cs
  extensions/Anthropic/Client/MessageResponse.cs
  extensions/Anthropic/Client/RawAnthropicClient.cs
  extensions/Anthropic/Client/StreamingResponseMessage.cs
  extensions/Anthropic/DependencyInjection.cs
  extensions/Anthropic/README.md
  service/Core/Core.csproj
  service/Core/KernelMemoryBuilder.cs
  service/Service/ServiceConfiguration.cs
  service/Service/appsettings.json
Labels: ready for review

#509 Reset stream position before posting to server
  clients/dotnet/WebClient/MemoryWebClient.cs
Labels: waiting for author

#504 Add batching upsert support to Qdrant Memory
  extensions/Qdrant/Qdrant/QdrantMemory.cs
Labels: ready for review
